[project]
name = "lang-fuse-setup"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "litellm>=1.77.7",
    "openai>=2.1.0",
    "pydantic-settings>=2.11.0",
]
